// Package openapi serves the API contract and its interactive Swagger UI.
package openapi

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.yaml
var spec []byte

//go:embed generated/swagger.yaml
var generatedSpec []byte

// Spec returns the OpenAPI 3 contract used by Swagger UI.
func Spec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/yaml; charset=utf-8")
	_, _ = w.Write(spec)
}

// GeneratedSpec returns the Swagger specification generated by swag from the
// annotations on the handlers.
func GeneratedSpec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/yaml; charset=utf-8")
	_, _ = w.Write(generatedSpec)
}

// UI exposes Swagger UI. Its JavaScript and CSS are loaded from jsDelivr, so
// the browser needs internet access when opening this page.
func UI(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(`<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><title>Mira API – Swagger</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css"></head>
<body><div id="swagger-ui"></div><script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
<script>SwaggerUIBundle({url:"/openapi.yaml",dom_id:"#swagger-ui",persistAuthorization:true});</script></body></html>`))
}
